### ISSUE TITLE
Is "gene product" in scope of MSO?

### ISSUE THREAD

**Issue by cmungall** [The-Sequence-Ontology/MSO#7]
GRO people need this. They are using FMA now, but FMA is human-specific

Is this in scope for MSO? Def could be `(RNA OR Protein) AND output_of some GO:gene_expression`

@jamesoverton @beckytauber we should also bring this into OBO-Core

Note in BL we also have:

 * https://biolink.github.io/biolink-model/docs/GeneOrGeneProduct.html
 * https://biolink.github.io/biolink-model/docs/MacromolecularMachine.html

Would be useful to have named classes for these in core

**Comment by mikebada** [comment]
Yes, a 'gene product' class has already been created (MSO:3000205); it's currently formally defined as the union of 'transcript' (MSO:0000673) and 'translational product' (MSO:3000263).
