### ISSUE TITLE
Add SO:0000235 TF_binding_site as a parent to a set of SO IDs

### ISSUE THREAD

**Issue by RLovering** [The-Sequence-Ontology/MSO#8]
Hi
At GO we are looking to merge a series of GO terms describing specific DNA binding see ticket https://github.com/geneontology/go-ontology/issues/16130#issuecomment-444944672 

It would be very helpful if the 'SO:0000235 TF_binding_site' could be added as a is_a parent to the following SO IDs

SO:0000235 TF_binding_site
> is_a child: SO_0001158 (E_box_motif)
> is_a child: SO_0001653 (retinoic_acid_responsive_element)

Thanks

Ruth

**Comment by mikebada** [comment]
Hi Ruth--yes, we can do this.

@mwatkin8 @nicoleruiz: Can you add the two is_a assertions above to the current public SO?  I'll correspondingly edit the MSO.

Cheers,
Mike

**Comment by nicoleruiz** [comment]
We can possibly get to this on Friday but mostly likely it will be early next week. We are in the middle of finals week and dissertation defenses over here. But I promise this will get looked at by next week!

**Comment by msinclair2** [comment]
Mike let me know when you're done editing master and I will do the reasoning and push the updated ontology files.
